"""Validate fixtures and outgoing payloads directly against the qlam-core models.

qlam-core ships no OpenAPI document; its pydantic models are generated from the
server specs (``# generated by datamodel-codegen``), so the models *are* the
wire contract available locally. Validating against them needs no extra
dependency, but two adjustments make the check describe the *server* rather
than the client:

* **Strict JSON-mode validation.** ``model_validate_json(..., strict=True)``
  refuses type coercion (``"100"`` is not an ``int``), reports missing required
  fields, and genuinely parses ``uuid`` and ``date-time`` values.
* **Undeclared-field detection.** The client models declare ``extra="allow"``,
  so pydantic silently accepts fields the server OpenAPI rejects
  (``additionalProperties: false`` on every task/definition object — see
  ``public_openapi.yml`` in qlam-task-manager and qlam-task-definitions).
  ``strict=True`` walks the payload against the model's declared fields so a
  stray key fails here instead of being dropped by the server. Use it for
  models bloqade *sends*; leave responses permissive, since what we *receive*
  may legitimately grow.

Payloads are serialized with ``model_dump(mode="json", exclude_none=True)``,
exactly as ``qlam_core.sdk.decorators`` serializes a request body, so tests
validate the bytes that actually go on the wire.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, ValidationError


def wire_payload(model: BaseModel) -> dict[str, Any]:
    """Serialize ``model`` the way ``qlam_core.sdk`` serializes a request body."""
    return model.model_dump(mode="json", exclude_none=True)


def declared_fields(model_cls: type[BaseModel]) -> set[str]:
    """Field names (and aliases) the model declares."""
    names: set[str] = set()
    for name, info in model_cls.model_fields.items():
        names.add(name)
        if info.alias:
            names.add(info.alias)
    return names


def required_fields(model_cls: type[BaseModel]) -> set[str]:
    return {n for n, f in model_cls.model_fields.items() if f.is_required()}


def undeclared_keys(model: BaseModel, payload: Any, path: str = "") -> list[str]:
    """Paths in ``payload`` that the validated ``model`` does not declare.

    Recurses through nested models, lists of models, and ``RootModel``
    wrappers (so a ``oneOf``-style request resolves to whichever variant
    pydantic selected). Plain-data fields such as ``arguments`` are not
    recursed into — their contents are values, not fields.
    """
    root = getattr(model, "root", None)
    if root is not None and "root" in type(model).model_fields:
        return undeclared_keys(root, payload, path)
    if not isinstance(payload, dict):
        return []

    declared = declared_fields(type(model))
    bad: list[str] = []
    for key, value in payload.items():
        here = f"{path}/{key}" if path else key
        if key not in declared:
            bad.append(here)
            continue
        sub = getattr(model, key, None)
        if isinstance(sub, BaseModel) and isinstance(value, dict):
            bad += undeclared_keys(sub, value, here)
        elif isinstance(sub, list) and isinstance(value, list):
            for i, (item, raw) in enumerate(zip(sub, value)):
                if isinstance(item, BaseModel) and isinstance(raw, dict):
                    bad += undeclared_keys(item, raw, f"{here}/{i}")
    return bad


def validation_errors(
    payload: Any, model_cls: type[BaseModel], *, strict: bool
) -> list[str]:
    """Human-readable violations of ``model_cls`` in ``payload`` (empty if valid).

    ``strict=True`` additionally reports fields the model does not declare.
    """
    try:
        model = model_cls.model_validate_json(json.dumps(payload), strict=True)
    except ValidationError as exc:
        return [
            f"{'/'.join(str(p) for p in e['loc']) or '<root>'}: {e['msg']}"
            for e in exc.errors()
        ]
    if not strict:
        return []
    return [f"{path}: undeclared field" for path in undeclared_keys(model, payload)]


def assert_valid(payload: Any, model_cls: type[BaseModel], *, strict: bool) -> None:
    errors = validation_errors(payload, model_cls, strict=strict)
    assert not errors, (
        f"payload does not match {model_cls.__name__} "
        f"(strict={strict}):\n  " + "\n  ".join(errors)
    )
